// Generated by gencpp from file testpkg/calc_areaRequest.msg
// DO NOT EDIT!


#ifndef TESTPKG_MESSAGE_CALC_AREAREQUEST_H
#define TESTPKG_MESSAGE_CALC_AREAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace testpkg
{
template <class ContainerAllocator>
struct calc_areaRequest_
{
  typedef calc_areaRequest_<ContainerAllocator> Type;

  calc_areaRequest_()
    : radius_array()  {
      radius_array.assign(0);
  }
  calc_areaRequest_(const ContainerAllocator& _alloc)
    : radius_array()  {
  (void)_alloc;
      radius_array.assign(0);
  }



   typedef boost::array<int64_t, 10>  _radius_array_type;
  _radius_array_type radius_array;





  typedef boost::shared_ptr< ::testpkg::calc_areaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::testpkg::calc_areaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct calc_areaRequest_

typedef ::testpkg::calc_areaRequest_<std::allocator<void> > calc_areaRequest;

typedef boost::shared_ptr< ::testpkg::calc_areaRequest > calc_areaRequestPtr;
typedef boost::shared_ptr< ::testpkg::calc_areaRequest const> calc_areaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::testpkg::calc_areaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::testpkg::calc_areaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace testpkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'testpkg': ['/home/euigeol/test_ws/src/testpkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::testpkg::calc_areaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::testpkg::calc_areaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testpkg::calc_areaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testpkg::calc_areaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testpkg::calc_areaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testpkg::calc_areaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::testpkg::calc_areaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d868a20f77b5a8769438c72cbf1e0323";
  }

  static const char* value(const ::testpkg::calc_areaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd868a20f77b5a876ULL;
  static const uint64_t static_value2 = 0x9438c72cbf1e0323ULL;
};

template<class ContainerAllocator>
struct DataType< ::testpkg::calc_areaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "testpkg/calc_areaRequest";
  }

  static const char* value(const ::testpkg::calc_areaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::testpkg::calc_areaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[10] radius_array\n\
";
  }

  static const char* value(const ::testpkg::calc_areaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::testpkg::calc_areaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radius_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct calc_areaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::testpkg::calc_areaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::testpkg::calc_areaRequest_<ContainerAllocator>& v)
  {
    s << indent << "radius_array[]" << std::endl;
    for (size_t i = 0; i < v.radius_array.size(); ++i)
    {
      s << indent << "  radius_array[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.radius_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESTPKG_MESSAGE_CALC_AREAREQUEST_H
