// Generated by gencpp from file testpkg/radiusArea.msg
// DO NOT EDIT!


#ifndef TESTPKG_MESSAGE_RADIUSAREA_H
#define TESTPKG_MESSAGE_RADIUSAREA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace testpkg
{
template <class ContainerAllocator>
struct radiusArea_
{
  typedef radiusArea_<ContainerAllocator> Type;

  radiusArea_()
    : header()
    , inarray(0)
    , outarray(0.0)  {
    }
  radiusArea_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , inarray(0)
    , outarray(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _inarray_type;
  _inarray_type inarray;

   typedef float _outarray_type;
  _outarray_type outarray;





  typedef boost::shared_ptr< ::testpkg::radiusArea_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::testpkg::radiusArea_<ContainerAllocator> const> ConstPtr;

}; // struct radiusArea_

typedef ::testpkg::radiusArea_<std::allocator<void> > radiusArea;

typedef boost::shared_ptr< ::testpkg::radiusArea > radiusAreaPtr;
typedef boost::shared_ptr< ::testpkg::radiusArea const> radiusAreaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::testpkg::radiusArea_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::testpkg::radiusArea_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace testpkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'testpkg': ['/home/euigeol/test_ws/src/testpkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::testpkg::radiusArea_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::testpkg::radiusArea_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testpkg::radiusArea_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testpkg::radiusArea_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testpkg::radiusArea_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testpkg::radiusArea_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::testpkg::radiusArea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63a322e2355ce289bef7e29c7fefb7e1";
  }

  static const char* value(const ::testpkg::radiusArea_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63a322e2355ce289ULL;
  static const uint64_t static_value2 = 0xbef7e29c7fefb7e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::testpkg::radiusArea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "testpkg/radiusArea";
  }

  static const char* value(const ::testpkg::radiusArea_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::testpkg::radiusArea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 inarray\n\
float32 outarray\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::testpkg::radiusArea_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::testpkg::radiusArea_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.inarray);
      stream.next(m.outarray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radiusArea_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::testpkg::radiusArea_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::testpkg::radiusArea_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "inarray: ";
    Printer<int32_t>::stream(s, indent + "  ", v.inarray);
    s << indent << "outarray: ";
    Printer<float>::stream(s, indent + "  ", v.outarray);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESTPKG_MESSAGE_RADIUSAREA_H
